# Generated by Django 4.0.3 on 2022-03-31 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_watch_remove_book_author_remove_book_genre_and_more'),
        ('order', '0002_remove_order_book_order_watch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='watch',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='main.brand'),
        ),
        migrations.AddField(
            model_name='watch',
            name='model',
            field=models.ManyToManyField(to='main.model'),
        ),
    ]
