# Generated by Django 4.0.3 on 2022-03-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_book_watch_brand_watch_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='main.brand'),
        ),
    ]
